<a href="https://colab.research.google.com/github/kaushal4445/GEN_AI-TRAINING-CGC-UNIVERSITY/blob/main/LEARNING_PYTHON/Gen_AI_Day7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#     **NUMPY**

Numpy is used for mathematical calculation for ML, DL and AI

Why Numpy ?

easy complex problem

efficient code

are used to store n- dimensional

perform indexed operation

is used to EDA(Explorating Data Analysis ) for ML, DL AND AI

to train machine by several operation to perform data -> numpy  --> EDA


In [ ]:
!pip install numpy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [ ]:
import numpy as np
n1 = np.array([12, 3, 4, 5])
print(n1)
print(n1.size)
print(type(n1))
print(n1.ndim)
#All execution are part  of EDA

[12  3  4  5]
4
<class 'numpy.ndarray'>
1


In [ ]:
n2 = np.array([[1, 2, 3, 4] , [5, 6, 7,8]])
print(n2)
print(n2.size)
print(type(n2))
print(n2.ndim)


[[1 2 3 4]
 [5 6 7 8]]
8
<class 'numpy.ndarray'>
2


# **Model always accept 2-D array**

In [ ]:
n3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(n3)
print(n3.size)
print(type(n3))
print(n3.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
9
<class 'numpy.ndarray'>
3


in case you 3-D array then must be convert into 2-D

then model trained

In [ ]:
n4 = np.array([[[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
               ]])
print(n4)
print(n4.size)
print(type(n4))
print(n4.ndim)

[[[[ 1  2  3]
   [ 4  5  6]
   [ 7  8  9]
   [10 11 12]]]]
12
<class 'numpy.ndarray'>
4


wHY  4D array not used or support

because 4d array is  high complexity and our eyes cannot see 4-D objects

In [ ]:
n5 = np.array(list(map(int, input("Enter elements").split())))
print(n5)

Enter elements    1 2 3 4 5 6 
[1 2 3 4 5 6]


# **IMPORTANT CODE**

In [ ]:
n = int(input("Enter number of elements :"))
n6 = np.array([int(input()) for i in range(n)])
print(n6)

Enter number of elements :3
1
2
3
[1 2 3]


In [ ]:
rows =int(input("Enter number of rows :"))
columns = int(input("Enter number of columns :"))
t = []
for i in range(rows):
  v = input("Enter elements:")
  t.append(v)
n7 = np.array(t)
print(n7)


Enter number of rows :2
Enter number of columns :2
Enter elements:4
Enter elements:1
['4' '1']


In [ ]:
rows =int(input("Enter number of rows :"))
columns = int(input("Enter number of columns :"))
t = []

print(f"Please enter {rows} rows, each with {columns} space-separated integers.")

for i in range(rows):
  t1 = []
for i in range(columns):
  c = list(map(int, input().split()))
  t1.append(c)
  t.append(t1)

n7 = np.array(t)
print(n7)

ValueError: invalid literal for int() with base 10: '1 2'

In [ ]:
z =

AttributeError: module 'numpy' has no attribute 'zeroes'

In [ ]:
# 7th what is the first work in ML
# shape and reshape
a1 = np.array([1, 2, 3, 4,5])
print(a1.shape)
a2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a2.shape)
s = a2.reshape(3, 3)
print(s)

(5,)
(9,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


next is age and salary(ins or deesc)

in product , if purchase 10000 then free delivery

in product, if purchase 5000 then the discount

is used for (ins or desc)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])
x = a+2
y= a*2
print(x)
print(y)

[3 4 5 6 7 8]
[ 2  4  6  8 10 12]


In [ ]:
a1 = np.array([1, 2, 3, 4], [5, 6,7,8])
a2 = np.array([11, 22, 33, 44])
z1 = a1  + a2
z2 = a1*a2
z3 = a1/a2
print(z1)
print(z2)
print(z3)

TypeError: Field elements must be 2- or 3-tuples, got '5'